import type {
  Client,
  FinanceSummary,
  Lead,
  Task,
  TeamMember,
  Transaction,
} from "@/lib/types";

/**
 * Dados mockados da Fase 1. Sem Supabase ainda — quando o MCP do banco
 * for conectado, isto vira uma query. A forma (campos) ja segue o modelo
 * final de Lead/Deal para nao quebrar a UI depois.
 */

export const TEAM: TeamMember[] = [
  { id: "u-ana", nome: "Ana Prado", iniciais: "AP", cor: "#45f0d1" },
  { id: "u-bruno", nome: "Bruno Lima", iniciais: "BL", cor: "#7c9cff" },
  { id: "u-carol", nome: "Carol Dias", iniciais: "CD", cor: "#c9ff3f" },
  { id: "u-diego", nome: "Diego Alves", iniciais: "DA", cor: "#ff8f6b" },
];

export const TEAM_BY_ID: Record<string, TeamMember> = Object.fromEntries(
  TEAM.map((m) => [m.id, m]),
);

/** dias atras -> ISO */
const d = (dias: number) =>
  new Date(Date.now() - dias * 86_400_000).toISOString();

export const LEADS: Lead[] = [
  {
    id: "l-01",
    nome: "Marina Costa",
    empresa: "Studio Norte Arquitetura",
    telefone: "+55 11 99812-4471",
    email: "marina@studionorte.com.br",
    site: "studionorte.com.br",
    segmento: "Arquitetura",
    tag: { label: "Inbound", color: "aqua" },
    stage: "lead",
    valor: 8500,
    responsavelId: "u-ana",
    atualizadoEm: d(1),
    origem: "Formulário do site",
  },
  {
    id: "l-02",
    nome: "Rafael Menezes",
    empresa: "Menezes Contabilidade",
    telefone: "+55 21 98123-9902",
    email: "rafael@menezescont.com.br",
    site: "menezescont.com.br",
    segmento: "Contabilidade",
    tag: { label: "Indicação", color: "lime" },
    stage: "lead",
    valor: 12000,
    responsavelId: "u-bruno",
    atualizadoEm: d(2),
    origem: "Indicação cliente",
  },
  {
    id: "l-03",
    nome: "Juliana Reis",
    empresa: "Clínica Vida Plena",
    telefone: "+55 31 99671-2234",
    email: "juliana@vidaplena.com.br",
    site: "vidaplena.com.br",
    segmento: "Saúde",
    tag: { label: "Prospecção IA", color: "violet" },
    stage: "lead",
    valor: 15000,
    responsavelId: "u-carol",
    atualizadoEm: d(3),
    origem: "Prospecção Inteligente",
  },
  {
    id: "l-04",
    nome: "Thiago Barros",
    empresa: "Barros Advogados",
    telefone: "+55 11 97744-1180",
    email: "contato@barrosadv.com.br",
    site: "barrosadv.com.br",
    segmento: "Jurídico",
    tag: { label: "Outbound", color: "blue" },
    stage: "primeira-chamada",
    valor: 9800,
    responsavelId: "u-ana",
    atualizadoEm: d(1),
  },
  {
    id: "l-05",
    nome: "Patrícia Gomes",
    empresa: "EcoVerde Paisagismo",
    telefone: "+55 41 99555-3321",
    email: "patricia@ecoverde.com.br",
    site: "ecoverde.com.br",
    segmento: "Paisagismo",
    tag: { label: "Inbound", color: "aqua" },
    stage: "primeira-chamada",
    valor: 6400,
    responsavelId: "u-diego",
    atualizadoEm: d(4),
  },
  {
    id: "l-06",
    nome: "Eduardo Nunes",
    empresa: "Nunes Consultoria",
    telefone: "+55 51 98890-7712",
    email: "eduardo@nunesconsult.com.br",
    site: "nunesconsult.com.br",
    segmento: "Consultoria",
    tag: { label: "Evento", color: "amber" },
    stage: "primeira-chamada",
    valor: 18500,
    responsavelId: "u-bruno",
    atualizadoEm: d(2),
  },
  {
    id: "l-07",
    nome: "Camila Ferreira",
    empresa: "Ferreira Odontologia",
    telefone: "+55 11 96622-8841",
    email: "camila@ferreiraodonto.com.br",
    site: "ferreiraodonto.com.br",
    segmento: "Saúde",
    tag: { label: "Indicação", color: "lime" },
    stage: "reuniao",
    valor: 11200,
    responsavelId: "u-carol",
    atualizadoEm: d(0),
  },
  {
    id: "l-08",
    nome: "Gustavo Pinto",
    empresa: "Pinto Corretora",
    telefone: "+55 21 99334-5567",
    email: "gustavo@pintocorretora.com.br",
    site: "pintocorretora.com.br",
    segmento: "Seguros",
    tag: { label: "Outbound", color: "blue" },
    stage: "reuniao",
    valor: 22000,
    responsavelId: "u-ana",
    atualizadoEm: d(1),
  },
  {
    id: "l-09",
    nome: "Larissa Souza",
    empresa: "Ateliê Souza",
    telefone: "+55 31 98812-4400",
    email: "larissa@ateliesouza.com.br",
    site: "ateliesouza.com.br",
    segmento: "Moda",
    tag: { label: "Inbound", color: "aqua" },
    stage: "proposta",
    valor: 7300,
    responsavelId: "u-diego",
    atualizadoEm: d(2),
    observacao: "Proposta enviada via gerador — aguardando retorno.",
  },
  {
    id: "l-10",
    nome: "Felipe Andrade",
    empresa: "Andrade Engenharia",
    telefone: "+55 11 97001-2213",
    email: "felipe@andradeeng.com.br",
    site: "andradeeng.com.br",
    segmento: "Engenharia",
    tag: { label: "Evento", color: "amber" },
    stage: "proposta",
    valor: 34000,
    responsavelId: "u-bruno",
    atualizadoEm: d(3),
    observacao: "Escopo grande, 2 fases.",
  },
  {
    id: "l-11",
    nome: "Beatriz Lopes",
    empresa: "Lopes Nutrição",
    telefone: "+55 41 99870-1122",
    email: "bia@lopesnutri.com.br",
    site: "lopesnutri.com.br",
    segmento: "Saúde",
    tag: { label: "Prospecção IA", color: "violet" },
    stage: "negociacao",
    valor: 9600,
    responsavelId: "u-carol",
    atualizadoEm: d(1),
    observacao: "Pedindo desconto de 10%.",
  },
  {
    id: "l-12",
    nome: "Rodrigo Tavares",
    empresa: "Tavares Auto Center",
    telefone: "+55 51 98123-9080",
    email: "rodrigo@tavaresauto.com.br",
    site: "tavaresauto.com.br",
    segmento: "Automotivo",
    tag: { label: "Indicação", color: "lime" },
    stage: "negociacao",
    valor: 16800,
    responsavelId: "u-ana",
    atualizadoEm: d(2),
  },
  {
    id: "l-13",
    nome: "Sônia Martins",
    empresa: "Martins Imóveis",
    telefone: "+55 11 96540-3322",
    email: "sonia@martinsimoveis.com.br",
    site: "martinsimoveis.com.br",
    segmento: "Imobiliário",
    tag: { label: "Outbound", color: "blue" },
    stage: "fechado",
    valor: 27500,
    responsavelId: "u-bruno",
    atualizadoEm: d(5),
    observacao: "Cobrança gerada no Asaas.",
  },
  {
    id: "l-14",
    nome: "André Carvalho",
    empresa: "Carvalho Marmoraria",
    telefone: "+55 31 99456-7781",
    email: "andre@carvalhomarmores.com.br",
    site: "carvalhomarmores.com.br",
    segmento: "Construção",
    tag: { label: "Inbound", color: "aqua" },
    stage: "fechado",
    valor: 13400,
    responsavelId: "u-diego",
    atualizadoEm: d(8),
  },
  {
    id: "l-15",
    nome: "Vanessa Rocha",
    empresa: "Rocha Eventos",
    telefone: "+55 21 98771-6650",
    email: "vanessa@rochaeventos.com.br",
    site: "rochaeventos.com.br",
    segmento: "Eventos",
    tag: { label: "Evento", color: "amber" },
    stage: "perdido",
    valor: 8900,
    responsavelId: "u-carol",
    atualizadoEm: d(12),
    observacao: "Foi com concorrente por preço.",
  },
  {
    id: "l-16",
    nome: "Marcos Vieira",
    empresa: "Vieira Transportes",
    telefone: "+55 41 99112-3345",
    email: "marcos@vieiratransportes.com.br",
    site: "vieiratransportes.com.br",
    segmento: "Logística",
    tag: { label: "Outbound", color: "slate" },
    stage: "perdido",
    valor: 19500,
    responsavelId: "u-ana",
    atualizadoEm: d(20),
    observacao: "Sem budget neste trimestre.",
  },
  {
    id: "l-17",
    nome: "Isabela Moreira",
    empresa: "Moreira Pet",
    telefone: "+55 11 95522-8890",
    email: "isabela@moreirapet.com.br",
    site: "moreirapet.com.br",
    segmento: "Pet",
    tag: { label: "Inbound", color: "aqua" },
    stage: "lead",
    valor: 5200,
    responsavelId: "u-diego",
    atualizadoEm: d(0),
  },
  {
    id: "l-18",
    nome: "Henrique Castro",
    empresa: "Castro Fotografia",
    telefone: "+55 31 98090-1123",
    email: "henrique@castrofoto.com.br",
    site: "castrofoto.com.br",
    segmento: "Fotografia",
    tag: { label: "Indicação", color: "lime" },
    stage: "reuniao",
    valor: 6900,
    responsavelId: "u-bruno",
    atualizadoEm: d(3),
  },
];

/* ==========================================================================
 * CLIENTES — negocios fechados. Os 2 primeiros sao os leads com
 * stage "fechado" promovidos a cliente; o resto e base historica mockada.
 * ======================================================================== */

export const CLIENTS: Client[] = [
  {
    id: "c-01",
    nome: "Sônia Martins",
    empresa: "Martins Imóveis",
    segmento: "Imobiliário",
    valorContrato: 27500,
    responsavelId: "u-bruno",
    status: "ativo",
    fechadoEm: d(5),
    origemLeadId: "l-13",
  },
  {
    id: "c-02",
    nome: "André Carvalho",
    empresa: "Carvalho Marmoraria",
    segmento: "Construção",
    valorContrato: 13400,
    responsavelId: "u-diego",
    status: "ativo",
    fechadoEm: d(8),
    origemLeadId: "l-14",
  },
  {
    id: "c-03",
    nome: "Renata Alves",
    empresa: "Alves & Filhos Distribuidora",
    segmento: "Distribuição",
    valorContrato: 42000,
    responsavelId: "u-ana",
    status: "ativo",
    fechadoEm: d(34),
  },
  {
    id: "c-04",
    nome: "Paulo Siqueira",
    empresa: "Siqueira Clínica Odontológica",
    segmento: "Saúde",
    valorContrato: 9800,
    responsavelId: "u-carol",
    status: "ativo",
    fechadoEm: d(61),
  },
  {
    id: "c-05",
    nome: "Fernanda Dantas",
    empresa: "Dantas Turismo",
    segmento: "Turismo",
    valorContrato: 15600,
    responsavelId: "u-ana",
    status: "pausado",
    fechadoEm: d(96),
  },
  {
    id: "c-06",
    nome: "Ricardo Moura",
    empresa: "Moura Logística",
    segmento: "Logística",
    valorContrato: 33500,
    responsavelId: "u-bruno",
    status: "ativo",
    fechadoEm: d(128),
  },
  {
    id: "c-07",
    nome: "Cláudia Neves",
    empresa: "Neves Papelaria",
    segmento: "Varejo",
    valorContrato: 6200,
    responsavelId: "u-diego",
    status: "encerrado",
    fechadoEm: d(210),
  },
];

export const CLIENTS_BY_ID: Record<string, Client> = Object.fromEntries(
  CLIENTS.map((c) => [c.id, c]),
);

/* ==========================================================================
 * TAREFAS — Kanban de producao de conteudo. `d(n)` = n dias atras,
 * `d(-n)` = n dias no futuro. Colunas: briefing / solicitacao /
 * em-producao / alteracao / pausa / aprovacao (ver src/lib/tasks.ts).
 *
 * Grafo de dependencias (dependsOn = ids que bloqueiam a task):
 *  - Chain A (video Alves & Filhos): t-01 -> t-02 -> t-03 ; t-01 -> t-06 ;
 *    (t-03, t-06) -> t-04 -> t-05      [diamante]
 *  - Chain B (social Dantas): t-07 (ATRASADA) -> t-08 -> t-09
 *  - Chain C (site Moura): t-10 -> t-11 -> t-12
 *  - t-13..t-18: sem dependencias (faixa de isolados no grafo)
 * ======================================================================== */

/** usuario logado simulado (para o filtro "Minhas") */
export const CURRENT_USER_ID = "u-ana";

export const TASKS: Task[] = [
  {
    id: "t-01",
    titulo: "Briefing da campanha de vídeo — Alves & Filhos",
    responsavelId: "u-ana",
    clienteId: "c-03",
    status: "briefing",
    prazo: d(1),
    prioridade: "alta",
    categoria: "Atendimento",
    briefing:
      "Levantar objetivos da campanha institucional com o cliente: público, tom, canais de veiculação e prazo de entrega. Consolidar num documento único que serve de base para roteiro e produção.\n\nCliente quer reforçar posicionamento premium e destacar a rede de distribuição própria.",
    referencias: [
      { label: "Ata da reunião de kickoff", url: "https://docs.google.com/document/d/1abc" },
      { label: "Site do cliente", url: "https://alvesefilhos.com.br" },
    ],
    dependsOn: [],
    subtarefas: [
      { id: "st-01a", label: "Enviar questionário de briefing", concluida: true },
      { id: "st-01b", label: "Reunião de alinhamento", concluida: true },
      { id: "st-01c", label: "Consolidar documento final", concluida: false },
    ],
    comentarios: [
      { autorId: "u-bruno", texto: "Cliente confirmou verba pra impulsionamento.", data: d(2) },
    ],
    aprovacao: { status: "pendente" },
    driveLink: "https://drive.google.com/drive/folders/alves-campanha",
    horasEstimadas: 6,
    registrosTempo: [
      { pessoaId: "u-ana", horas: 2, data: d(3) },
      { pessoaId: "u-ana", horas: 1.5, data: d(1) },
    ],
  },
  {
    id: "t-02",
    titulo: "Roteiro do vídeo institucional",
    responsavelId: "u-carol",
    clienteId: "c-03",
    status: "em-producao",
    prazo: d(-2),
    prioridade: "alta",
    categoria: "Design",
    briefing:
      "Escrever roteiro de 90s a partir do briefing aprovado: abertura com dor do mercado, virada com a solução do cliente, prova social e CTA. Marcar cenas para a captação.",
    referencias: [
      { label: "Referência de tom (YouTube)", url: "https://youtube.com/watch?v=xyz" },
      { label: "Board no Figma", url: "https://figma.com/file/roteiro-alves" },
    ],
    dependsOn: ["t-01"],
    subtarefas: [
      { id: "st-02a", label: "Primeira versão do roteiro", concluida: true },
      { id: "st-02b", label: "Revisão interna", concluida: false },
      { id: "st-02c", label: "Lista de cenas para gravação", concluida: false },
    ],
    comentarios: [],
    aprovacao: { status: "pendente" },
    driveLink: "https://drive.google.com/drive/folders/alves-campanha",
    horasEstimadas: 10,
    registrosTempo: [
      { pessoaId: "u-carol", horas: 4, data: d(4) },
      { pessoaId: "u-carol", horas: 3, data: d(2) },
    ],
  },
  {
    id: "t-03",
    titulo: "Gravação e captação de imagens",
    responsavelId: "u-diego",
    clienteId: "c-03",
    status: "solicitacao",
    prazo: d(-5),
    prioridade: "media",
    categoria: "Design",
    briefing:
      "Diária de captação no centro de distribuição do cliente. Registrar operação, fachada, equipe e depoimento do diretor. Backup do material no Drive no mesmo dia.",
    referencias: [
      { label: "Lista de planos", url: "https://docs.google.com/spreadsheets/d/planos" },
    ],
    dependsOn: ["t-02"],
    subtarefas: [
      { id: "st-03a", label: "Confirmar agenda com o cliente", concluida: true },
      { id: "st-03b", label: "Checklist de equipamento", concluida: false },
      { id: "st-03c", label: "Upload e organização do bruto", concluida: false },
    ],
    comentarios: [],
    aprovacao: { status: "pendente" },
    horasEstimadas: 8,
    registrosTempo: [],
  },
  {
    id: "t-04",
    titulo: "Edição do vídeo institucional",
    responsavelId: "u-diego",
    clienteId: "c-03",
    status: "em-producao",
    prazo: d(-8),
    prioridade: "urgente",
    categoria: "Design",
    briefing:
      "Montar o corte final com base no roteiro e na trilha aprovada. Color grading, legendas e versões 16:9 e 9:16 para social.",
    referencias: [
      { label: "Projeto no Frame.io", url: "https://frame.io/alves-edicao" },
    ],
    dependsOn: ["t-03", "t-06"],
    subtarefas: [
      { id: "st-04a", label: "Corte bruto (V1)", concluida: false },
      { id: "st-04b", label: "Color grading", concluida: false },
      { id: "st-04c", label: "Versões vertical/horizontal", concluida: false },
      { id: "st-04d", label: "Legendas", concluida: false },
    ],
    comentarios: [
      { autorId: "u-ana", texto: "Prazo apertou — priorizar a versão 16:9.", data: d(1) },
    ],
    aprovacao: { status: "pendente" },
    driveLink: "https://drive.google.com/drive/folders/alves-campanha",
    horasEstimadas: 16,
    registrosTempo: [{ pessoaId: "u-diego", horas: 2, data: d(1) }],
  },
  {
    id: "t-05",
    titulo: "Aprovação final do vídeo — cliente",
    responsavelId: "u-ana",
    clienteId: "c-03",
    status: "aprovacao",
    prazo: d(-12),
    prioridade: "alta",
    categoria: "Atendimento",
    briefing:
      "Enviar corte final para o cliente, coletar ajustes por timestamp e obter aprovação formal por e-mail antes da entrega dos arquivos.",
    referencias: [],
    dependsOn: ["t-04"],
    subtarefas: [
      { id: "st-05a", label: "Enviar link de revisão", concluida: false },
      { id: "st-05b", label: "Consolidar ajustes", concluida: false },
    ],
    comentarios: [],
    aprovacao: { status: "pendente" },
    horasEstimadas: 3,
    registrosTempo: [],
  },
  {
    id: "t-06",
    titulo: "Trilha sonora e locução",
    responsavelId: "u-diego",
    clienteId: "c-03",
    status: "em-producao",
    prazo: d(-4),
    prioridade: "media",
    categoria: "Design",
    briefing:
      "Selecionar trilha licenciada alinhada ao tom premium e gravar locução em off com o roteiro aprovado. Entregar stems separados para a edição.",
    referencias: [
      { label: "Playlist de referência", url: "https://open.spotify.com/playlist/abc" },
    ],
    dependsOn: ["t-01"],
    subtarefas: [
      { id: "st-06a", label: "Escolher 3 opções de trilha", concluida: true },
      { id: "st-06b", label: "Gravar locução", concluida: false },
    ],
    comentarios: [],
    aprovacao: { status: "pendente" },
    horasEstimadas: 5,
    registrosTempo: [{ pessoaId: "u-diego", horas: 1.5, data: d(5) }],
  },
  {
    id: "t-07",
    titulo: "Definir paleta visual e tom — Dantas Turismo",
    responsavelId: "u-carol",
    clienteId: "c-05",
    status: "alteracao",
    prazo: d(6),
    prioridade: "urgente",
    categoria: "Design",
    briefing:
      "Fechar identidade visual do social do cliente: paleta, tipografia e grid dos posts. Cliente pediu ajustes na primeira proposta — refazer com tons mais quentes.",
    referencias: [
      { label: "Moodboard", url: "https://figma.com/file/dantas-moodboard" },
      { label: "Feedback do cliente", url: "https://docs.google.com/document/d/dantas-feedback" },
    ],
    dependsOn: [],
    subtarefas: [
      { id: "st-07a", label: "Proposta V1", concluida: true },
      { id: "st-07b", label: "Incorporar feedback", concluida: false },
      { id: "st-07c", label: "Guia de estilo final", concluida: false },
    ],
    comentarios: [
      { autorId: "u-ana", texto: "Cliente está esperando isso pra ontem, segura a peteca.", data: d(2) },
    ],
    aprovacao: { status: "devolvida", por: "u-ana", comentario: "Ajustar contraste e trocar a fonte de título." },
    driveLink: "https://drive.google.com/drive/folders/dantas-social",
    horasEstimadas: 8,
    registrosTempo: [
      { pessoaId: "u-carol", horas: 5, data: d(9) },
      { pessoaId: "u-carol", horas: 2, data: d(3) },
    ],
  },
  {
    id: "t-08",
    titulo: "Kit de templates de posts",
    responsavelId: "u-carol",
    clienteId: "c-05",
    status: "em-producao",
    prazo: d(-3),
    prioridade: "alta",
    categoria: "Design",
    briefing:
      "Montar 6 templates editáveis no Figma (feed, carrossel e stories) seguindo o guia de estilo aprovado. Preparar para entrega ao cliente com biblioteca de componentes.",
    referencias: [{ label: "Arquivo de templates", url: "https://figma.com/file/dantas-templates" }],
    dependsOn: ["t-07"],
    subtarefas: [
      { id: "st-08a", label: "Template de feed", concluida: false },
      { id: "st-08b", label: "Template de carrossel", concluida: false },
      { id: "st-08c", label: "Template de stories", concluida: false },
    ],
    comentarios: [],
    aprovacao: { status: "pendente" },
    horasEstimadas: 12,
    registrosTempo: [{ pessoaId: "u-carol", horas: 3, data: d(6) }],
  },
  {
    id: "t-09",
    titulo: "Agendar calendário de posts do mês",
    responsavelId: "u-bruno",
    clienteId: "c-05",
    status: "solicitacao",
    prazo: d(-1),
    prioridade: "media",
    categoria: "Atendimento",
    briefing:
      "Com os templates prontos, montar o calendário editorial do mês, redigir legendas e programar as publicações na ferramenta de agendamento.",
    referencias: [
      { label: "Calendário editorial", url: "https://docs.google.com/spreadsheets/d/dantas-calendario" },
    ],
    dependsOn: ["t-08"],
    subtarefas: [
      { id: "st-09a", label: "Redigir legendas", concluida: false },
      { id: "st-09b", label: "Programar publicações", concluida: false },
    ],
    comentarios: [],
    aprovacao: { status: "pendente" },
    horasEstimadas: 6,
    registrosTempo: [],
  },
  {
    id: "t-10",
    titulo: "Levantamento de requisitos do site — Moura Logística",
    responsavelId: "u-bruno",
    clienteId: "c-06",
    status: "briefing",
    prazo: d(3),
    prioridade: "media",
    categoria: "Desenvolvimento",
    briefing:
      "Mapear páginas, integrações (rastreio de carga, formulário de cotação) e conteúdo necessário para o novo site institucional do cliente.",
    referencias: [
      { label: "Site atual", url: "https://mouralog.com.br" },
      { label: "Documento de requisitos", url: "https://docs.google.com/document/d/moura-req" },
    ],
    dependsOn: [],
    subtarefas: [
      { id: "st-10a", label: "Inventário de conteúdo", concluida: true },
      { id: "st-10b", label: "Mapa do site", concluida: false },
      { id: "st-10c", label: "Lista de integrações", concluida: false },
    ],
    comentarios: [],
    aprovacao: { status: "pendente" },
    horasEstimadas: 7,
    registrosTempo: [{ pessoaId: "u-bruno", horas: 2, data: d(4) }],
  },
  {
    id: "t-11",
    titulo: "Wireframes das páginas internas",
    responsavelId: "u-carol",
    clienteId: "c-06",
    status: "em-producao",
    prazo: d(-2),
    prioridade: "media",
    categoria: "Design",
    briefing:
      "Desenhar wireframes de baixa fidelidade das 5 páginas internas priorizadas no levantamento. Foco em hierarquia de informação, não em visual.",
    referencias: [{ label: "Wireframes no Figma", url: "https://figma.com/file/moura-wireframes" }],
    dependsOn: ["t-10"],
    subtarefas: [
      { id: "st-11a", label: "Home", concluida: true },
      { id: "st-11b", label: "Serviços", concluida: false },
      { id: "st-11c", label: "Rastreio", concluida: false },
      { id: "st-11d", label: "Contato", concluida: false },
    ],
    comentarios: [],
    aprovacao: { status: "pendente" },
    driveLink: "https://drive.google.com/drive/folders/moura-site",
    horasEstimadas: 10,
    registrosTempo: [{ pessoaId: "u-carol", horas: 4, data: d(3) }],
  },
  {
    id: "t-12",
    titulo: "Implementação do front-end",
    responsavelId: "u-bruno",
    clienteId: "c-06",
    status: "solicitacao",
    prazo: d(-9),
    prioridade: "alta",
    categoria: "Desenvolvimento",
    briefing:
      "Implementar o site em Next.js a partir dos wireframes aprovados e do layout final. Responsivo, com CMS leve para o time do cliente editar textos.",
    referencias: [{ label: "Repositório", url: "https://github.com/emerge/moura-site" }],
    dependsOn: ["t-11"],
    subtarefas: [
      { id: "st-12a", label: "Setup do projeto", concluida: false },
      { id: "st-12b", label: "Componentes base", concluida: false },
      { id: "st-12c", label: "Integração do CMS", concluida: false },
    ],
    comentarios: [],
    aprovacao: { status: "pendente" },
    horasEstimadas: 24,
    registrosTempo: [],
  },
  {
    id: "t-13",
    titulo: "Revisar cobrança Asaas do mês",
    responsavelId: "u-ana",
    status: "em-producao",
    prazo: d(-1),
    prioridade: "media",
    categoria: "Financeiro",
    briefing:
      "Conferir todas as cobranças geradas no Asaas contra os contratos ativos, identificar divergências e reenviar boletos vencidos.",
    referencias: [{ label: "Painel Asaas", url: "https://www.asaas.com/login" }],
    dependsOn: [],
    subtarefas: [
      { id: "st-13a", label: "Bater cobranças x contratos", concluida: true },
      { id: "st-13b", label: "Reenviar vencidos", concluida: false },
    ],
    comentarios: [],
    aprovacao: { status: "pendente" },
    horasEstimadas: 3,
    registrosTempo: [{ pessoaId: "u-ana", horas: 1, data: d(1) }],
  },
  {
    id: "t-14",
    titulo: "Compilar métricas de prospecção da semana",
    responsavelId: "u-carol",
    status: "aprovacao",
    prazo: d(2),
    prioridade: "baixa",
    categoria: "Prospecção",
    briefing:
      "Consolidar número de leads novos, reuniões marcadas e propostas enviadas na semana. Gerar o resumo para a reunião de segunda.",
    referencias: [],
    dependsOn: [],
    subtarefas: [
      { id: "st-14a", label: "Puxar dados do pipeline", concluida: true },
      { id: "st-14b", label: "Montar resumo", concluida: true },
    ],
    comentarios: [],
    aprovacao: { status: "aprovada", por: "u-bruno" },
    horasEstimadas: 2,
    registrosTempo: [{ pessoaId: "u-carol", horas: 2, data: d(2) }],
    meta: {
      label: "Propostas enviadas na semana",
      valorAlvo: 10,
      valorAtual: 6,
      unidade: "propostas",
    },
  },
  {
    id: "t-15",
    titulo: "Onboarding do contrato — Martins Imóveis",
    responsavelId: "u-bruno",
    clienteId: "c-01",
    status: "em-producao",
    prazo: d(-3),
    prioridade: "alta",
    categoria: "Atendimento",
    briefing:
      "Rodar o checklist de onboarding do novo cliente: acessos, reunião de kickoff, definição de canais de comunicação e primeiro planejamento mensal.",
    referencias: [
      { label: "Checklist de onboarding", url: "https://www.notion.so/emerge/onboarding" },
    ],
    dependsOn: [],
    subtarefas: [
      { id: "st-15a", label: "Coletar acessos", concluida: true },
      { id: "st-15b", label: "Kickoff", concluida: true },
      { id: "st-15c", label: "Planejamento do mês 1", concluida: false },
    ],
    comentarios: [
      { autorId: "u-diego", texto: "Cliente já mandou os acessos do Instagram.", data: d(4) },
    ],
    aprovacao: { status: "pendente" },
    driveLink: "https://drive.google.com/drive/folders/martins-onboarding",
    horasEstimadas: 5,
    registrosTempo: [{ pessoaId: "u-bruno", horas: 3, data: d(5) }],
  },
  {
    id: "t-16",
    titulo: "Atualizar catálogo de serviços no site da Emerge",
    responsavelId: "u-diego",
    status: "pausa",
    prazo: d(-10),
    prioridade: "baixa",
    categoria: "Desenvolvimento",
    briefing:
      "Revisar textos e preços da página de Serviços do site institucional da Emerge. Pausado até o time comercial fechar a nova tabela.",
    referencias: [],
    dependsOn: [],
    subtarefas: [{ id: "st-16a", label: "Aguardar tabela nova do comercial", concluida: false }],
    comentarios: [
      { autorId: "u-ana", texto: "Comercial fecha a tabela só semana que vem.", data: d(6) },
    ],
    aprovacao: { status: "pendente" },
    horasEstimadas: 3,
    registrosTempo: [],
  },
  {
    id: "t-17",
    titulo: "Follow-up de renovação — Dantas Turismo",
    responsavelId: "u-ana",
    clienteId: "c-05",
    status: "briefing",
    prazo: d(-4),
    prioridade: "alta",
    categoria: "Atendimento",
    briefing:
      "Contrato do cliente está pausado. Agendar conversa de renovação, entender o que travou e propor novo escopo mais enxuto.",
    referencias: [],
    dependsOn: [],
    subtarefas: [
      { id: "st-17a", label: "Enviar mensagem propondo call", concluida: false },
      { id: "st-17b", label: "Preparar proposta de renovação", concluida: false },
    ],
    comentarios: [],
    aprovacao: { status: "pendente" },
    horasEstimadas: 4,
    registrosTempo: [],
  },
  {
    id: "t-18",
    titulo: "Ligar para leads indicados da semana",
    responsavelId: "u-bruno",
    status: "solicitacao",
    prazo: d(0),
    prioridade: "media",
    categoria: "Prospecção",
    briefing:
      "Fazer o primeiro contato com os 8 leads que chegaram por indicação nos últimos dias. Registrar resultado de cada ligação no pipeline.",
    referencias: [],
    dependsOn: [],
    subtarefas: [
      { id: "st-18a", label: "Preparar roteiro de ligação", concluida: true },
      { id: "st-18b", label: "Ligar (0/8)", concluida: false },
    ],
    comentarios: [],
    aprovacao: { status: "pendente" },
    horasEstimadas: 4,
    registrosTempo: [{ pessoaId: "u-bruno", horas: 1, data: d(0) }],
    meta: {
      label: "Ligações de prospecção",
      valorAlvo: 8,
      valorAtual: 3,
      unidade: "ligações",
    },
  },
];

/* ==========================================================================
 * FINANCEIRO — resumo + transacoes recentes (numeros mockados plausiveis).
 * ======================================================================== */

export const FINANCE_SUMMARY: FinanceSummary = {
  caixaAtual: 184300,
  aReceber: 96700,
  receitaMes: 71250,
  taxaInadimplencia: 0.086,
};

export const TRANSACTIONS: Transaction[] = [
  {
    id: "tx-01",
    descricao: "Mensalidade — contrato Martins Imóveis",
    parte: "Martins Imóveis",
    valor: 27500,
    tipo: "entrada",
    data: d(1),
    status: "pago",
  },
  {
    id: "tx-02",
    descricao: "Entrada — proposta fechada Carvalho Marmoraria",
    parte: "Carvalho Marmoraria",
    valor: 13400,
    tipo: "entrada",
    data: d(3),
    status: "pago",
  },
  {
    id: "tx-03",
    descricao: "Assinatura de ferramentas (Google Workspace)",
    parte: "Google",
    valor: 890,
    tipo: "saida",
    data: d(4),
    status: "pago",
  },
  {
    id: "tx-04",
    descricao: "Mensalidade — Alves & Filhos Distribuidora",
    parte: "Alves & Filhos Distribuidora",
    valor: 42000,
    tipo: "entrada",
    data: d(6),
    status: "pendente",
  },
  {
    id: "tx-05",
    descricao: "Anúncios — captação de leads (Meta Ads)",
    parte: "Meta",
    valor: 3200,
    tipo: "saida",
    data: d(7),
    status: "pago",
  },
  {
    id: "tx-06",
    descricao: "Mensalidade — Siqueira Clínica Odontológica",
    parte: "Siqueira Clínica Odontológica",
    valor: 9800,
    tipo: "entrada",
    data: d(9),
    status: "pago",
  },
  {
    id: "tx-07",
    descricao: "Mensalidade — Moura Logística",
    parte: "Moura Logística",
    valor: 33500,
    tipo: "entrada",
    data: d(11),
    status: "pendente",
  },
  {
    id: "tx-08",
    descricao: "Hospedagem e domínio (Vercel + registro)",
    parte: "Vercel",
    valor: 640,
    tipo: "saida",
    data: d(12),
    status: "pago",
  },
  {
    id: "tx-09",
    descricao: "Mensalidade — Dantas Turismo",
    parte: "Dantas Turismo",
    valor: 15600,
    tipo: "entrada",
    data: d(14),
    status: "pendente",
  },
  {
    id: "tx-10",
    descricao: "Pró-labore e salários",
    parte: "Equipe Emerge",
    valor: 38000,
    tipo: "saida",
    data: d(15),
    status: "pago",
  },
];
