import type {
  Client,
  FinanceSummary,
  Lead,
  Task,
  TeamMember,
  Transaction,
} from "@/lib/types";

/**
 * Dados mockados da Fase 1. Sem Supabase ainda — quando o MCP do banco
 * for conectado, isto vira uma query. A forma (campos) ja segue o modelo
 * final de Lead/Deal para nao quebrar a UI depois.
 */

export const TEAM: TeamMember[] = [
  { id: "u-ana", nome: "Ana Prado", iniciais: "AP", cor: "#45f0d1" },
  { id: "u-bruno", nome: "Bruno Lima", iniciais: "BL", cor: "#7c9cff" },
  { id: "u-carol", nome: "Carol Dias", iniciais: "CD", cor: "#c9ff3f" },
  { id: "u-diego", nome: "Diego Alves", iniciais: "DA", cor: "#ff8f6b" },
];

export const TEAM_BY_ID: Record<string, TeamMember> = Object.fromEntries(
  TEAM.map((m) => [m.id, m]),
);

/** dias atras -> ISO */
const d = (dias: number) =>
  new Date(Date.now() - dias * 86_400_000).toISOString();

export const LEADS: Lead[] = [
  {
    id: "l-01",
    nome: "Marina Costa",
    empresa: "Studio Norte Arquitetura",
    telefone: "+55 11 99812-4471",
    email: "marina@studionorte.com.br",
    site: "studionorte.com.br",
    segmento: "Arquitetura",
    tag: { label: "Inbound", color: "aqua" },
    stage: "lead",
    valor: 8500,
    responsavelId: "u-ana",
    atualizadoEm: d(1),
    origem: "Formulário do site",
  },
  {
    id: "l-02",
    nome: "Rafael Menezes",
    empresa: "Menezes Contabilidade",
    telefone: "+55 21 98123-9902",
    email: "rafael@menezescont.com.br",
    site: "menezescont.com.br",
    segmento: "Contabilidade",
    tag: { label: "Indicação", color: "lime" },
    stage: "lead",
    valor: 12000,
    responsavelId: "u-bruno",
    atualizadoEm: d(2),
    origem: "Indicação cliente",
  },
  {
    id: "l-03",
    nome: "Juliana Reis",
    empresa: "Clínica Vida Plena",
    telefone: "+55 31 99671-2234",
    email: "juliana@vidaplena.com.br",
    site: "vidaplena.com.br",
    segmento: "Saúde",
    tag: { label: "Prospecção IA", color: "violet" },
    stage: "lead",
    valor: 15000,
    responsavelId: "u-carol",
    atualizadoEm: d(3),
    origem: "Prospecção Inteligente",
  },
  {
    id: "l-04",
    nome: "Thiago Barros",
    empresa: "Barros Advogados",
    telefone: "+55 11 97744-1180",
    email: "contato@barrosadv.com.br",
    site: "barrosadv.com.br",
    segmento: "Jurídico",
    tag: { label: "Outbound", color: "blue" },
    stage: "primeira-chamada",
    valor: 9800,
    responsavelId: "u-ana",
    atualizadoEm: d(1),
  },
  {
    id: "l-05",
    nome: "Patrícia Gomes",
    empresa: "EcoVerde Paisagismo",
    telefone: "+55 41 99555-3321",
    email: "patricia@ecoverde.com.br",
    site: "ecoverde.com.br",
    segmento: "Paisagismo",
    tag: { label: "Inbound", color: "aqua" },
    stage: "primeira-chamada",
    valor: 6400,
    responsavelId: "u-diego",
    atualizadoEm: d(4),
  },
  {
    id: "l-06",
    nome: "Eduardo Nunes",
    empresa: "Nunes Consultoria",
    telefone: "+55 51 98890-7712",
    email: "eduardo@nunesconsult.com.br",
    site: "nunesconsult.com.br",
    segmento: "Consultoria",
    tag: { label: "Evento", color: "amber" },
    stage: "primeira-chamada",
    valor: 18500,
    responsavelId: "u-bruno",
    atualizadoEm: d(2),
  },
  {
    id: "l-07",
    nome: "Camila Ferreira",
    empresa: "Ferreira Odontologia",
    telefone: "+55 11 96622-8841",
    email: "camila@ferreiraodonto.com.br",
    site: "ferreiraodonto.com.br",
    segmento: "Saúde",
    tag: { label: "Indicação", color: "lime" },
    stage: "reuniao",
    valor: 11200,
    responsavelId: "u-carol",
    atualizadoEm: d(0),
  },
  {
    id: "l-08",
    nome: "Gustavo Pinto",
    empresa: "Pinto Corretora",
    telefone: "+55 21 99334-5567",
    email: "gustavo@pintocorretora.com.br",
    site: "pintocorretora.com.br",
    segmento: "Seguros",
    tag: { label: "Outbound", color: "blue" },
    stage: "reuniao",
    valor: 22000,
    responsavelId: "u-ana",
    atualizadoEm: d(1),
  },
  {
    id: "l-09",
    nome: "Larissa Souza",
    empresa: "Ateliê Souza",
    telefone: "+55 31 98812-4400",
    email: "larissa@ateliesouza.com.br",
    site: "ateliesouza.com.br",
    segmento: "Moda",
    tag: { label: "Inbound", color: "aqua" },
    stage: "proposta",
    valor: 7300,
    responsavelId: "u-diego",
    atualizadoEm: d(2),
    observacao: "Proposta enviada via gerador — aguardando retorno.",
  },
  {
    id: "l-10",
    nome: "Felipe Andrade",
    empresa: "Andrade Engenharia",
    telefone: "+55 11 97001-2213",
    email: "felipe@andradeeng.com.br",
    site: "andradeeng.com.br",
    segmento: "Engenharia",
    tag: { label: "Evento", color: "amber" },
    stage: "proposta",
    valor: 34000,
    responsavelId: "u-bruno",
    atualizadoEm: d(3),
    observacao: "Escopo grande, 2 fases.",
  },
  {
    id: "l-11",
    nome: "Beatriz Lopes",
    empresa: "Lopes Nutrição",
    telefone: "+55 41 99870-1122",
    email: "bia@lopesnutri.com.br",
    site: "lopesnutri.com.br",
    segmento: "Saúde",
    tag: { label: "Prospecção IA", color: "violet" },
    stage: "negociacao",
    valor: 9600,
    responsavelId: "u-carol",
    atualizadoEm: d(1),
    observacao: "Pedindo desconto de 10%.",
  },
  {
    id: "l-12",
    nome: "Rodrigo Tavares",
    empresa: "Tavares Auto Center",
    telefone: "+55 51 98123-9080",
    email: "rodrigo@tavaresauto.com.br",
    site: "tavaresauto.com.br",
    segmento: "Automotivo",
    tag: { label: "Indicação", color: "lime" },
    stage: "negociacao",
    valor: 16800,
    responsavelId: "u-ana",
    atualizadoEm: d(2),
  },
  {
    id: "l-13",
    nome: "Sônia Martins",
    empresa: "Martins Imóveis",
    telefone: "+55 11 96540-3322",
    email: "sonia@martinsimoveis.com.br",
    site: "martinsimoveis.com.br",
    segmento: "Imobiliário",
    tag: { label: "Outbound", color: "blue" },
    stage: "fechado",
    valor: 27500,
    responsavelId: "u-bruno",
    atualizadoEm: d(5),
    observacao: "Cobrança gerada no Asaas.",
  },
  {
    id: "l-14",
    nome: "André Carvalho",
    empresa: "Carvalho Marmoraria",
    telefone: "+55 31 99456-7781",
    email: "andre@carvalhomarmores.com.br",
    site: "carvalhomarmores.com.br",
    segmento: "Construção",
    tag: { label: "Inbound", color: "aqua" },
    stage: "fechado",
    valor: 13400,
    responsavelId: "u-diego",
    atualizadoEm: d(8),
  },
  {
    id: "l-15",
    nome: "Vanessa Rocha",
    empresa: "Rocha Eventos",
    telefone: "+55 21 98771-6650",
    email: "vanessa@rochaeventos.com.br",
    site: "rochaeventos.com.br",
    segmento: "Eventos",
    tag: { label: "Evento", color: "amber" },
    stage: "perdido",
    valor: 8900,
    responsavelId: "u-carol",
    atualizadoEm: d(12),
    observacao: "Foi com concorrente por preço.",
  },
  {
    id: "l-16",
    nome: "Marcos Vieira",
    empresa: "Vieira Transportes",
    telefone: "+55 41 99112-3345",
    email: "marcos@vieiratransportes.com.br",
    site: "vieiratransportes.com.br",
    segmento: "Logística",
    tag: { label: "Outbound", color: "slate" },
    stage: "perdido",
    valor: 19500,
    responsavelId: "u-ana",
    atualizadoEm: d(20),
    observacao: "Sem budget neste trimestre.",
  },
  {
    id: "l-17",
    nome: "Isabela Moreira",
    empresa: "Moreira Pet",
    telefone: "+55 11 95522-8890",
    email: "isabela@moreirapet.com.br",
    site: "moreirapet.com.br",
    segmento: "Pet",
    tag: { label: "Inbound", color: "aqua" },
    stage: "lead",
    valor: 5200,
    responsavelId: "u-diego",
    atualizadoEm: d(0),
  },
  {
    id: "l-18",
    nome: "Henrique Castro",
    empresa: "Castro Fotografia",
    telefone: "+55 31 98090-1123",
    email: "henrique@castrofoto.com.br",
    site: "castrofoto.com.br",
    segmento: "Fotografia",
    tag: { label: "Indicação", color: "lime" },
    stage: "reuniao",
    valor: 6900,
    responsavelId: "u-bruno",
    atualizadoEm: d(3),
  },
];

/* ==========================================================================
 * CLIENTES — negocios fechados. Os 2 primeiros sao os leads com
 * stage "fechado" promovidos a cliente; o resto e base historica mockada.
 * ======================================================================== */

export const CLIENTS: Client[] = [
  {
    id: "c-01",
    nome: "Sônia Martins",
    empresa: "Martins Imóveis",
    segmento: "Imobiliário",
    valorContrato: 27500,
    responsavelId: "u-bruno",
    status: "ativo",
    fechadoEm: d(5),
    origemLeadId: "l-13",
  },
  {
    id: "c-02",
    nome: "André Carvalho",
    empresa: "Carvalho Marmoraria",
    segmento: "Construção",
    valorContrato: 13400,
    responsavelId: "u-diego",
    status: "ativo",
    fechadoEm: d(8),
    origemLeadId: "l-14",
  },
  {
    id: "c-03",
    nome: "Renata Alves",
    empresa: "Alves & Filhos Distribuidora",
    segmento: "Distribuição",
    valorContrato: 42000,
    responsavelId: "u-ana",
    status: "ativo",
    fechadoEm: d(34),
  },
  {
    id: "c-04",
    nome: "Paulo Siqueira",
    empresa: "Siqueira Clínica Odontológica",
    segmento: "Saúde",
    valorContrato: 9800,
    responsavelId: "u-carol",
    status: "ativo",
    fechadoEm: d(61),
  },
  {
    id: "c-05",
    nome: "Fernanda Dantas",
    empresa: "Dantas Turismo",
    segmento: "Turismo",
    valorContrato: 15600,
    responsavelId: "u-ana",
    status: "pausado",
    fechadoEm: d(96),
  },
  {
    id: "c-06",
    nome: "Ricardo Moura",
    empresa: "Moura Logística",
    segmento: "Logística",
    valorContrato: 33500,
    responsavelId: "u-bruno",
    status: "ativo",
    fechadoEm: d(128),
  },
  {
    id: "c-07",
    nome: "Cláudia Neves",
    empresa: "Neves Papelaria",
    segmento: "Varejo",
    valorContrato: 6200,
    responsavelId: "u-diego",
    status: "encerrado",
    fechadoEm: d(210),
  },
];

export const CLIENTS_BY_ID: Record<string, Client> = Object.fromEntries(
  CLIENTS.map((c) => [c.id, c]),
);

/* ==========================================================================
 * TAREFAS — lista de tasks da equipe. `d(-n)` = n dias no futuro.
 * ======================================================================== */

export const TASKS: Task[] = [
  {
    id: "t-01",
    titulo: "Enviar proposta revisada para Ateliê Souza",
    responsavelId: "u-diego",
    status: "em-andamento",
    prazo: d(-1),
    prioridade: "alta",
  },
  {
    id: "t-02",
    titulo: "Follow-up com Beatriz Lopes sobre desconto",
    responsavelId: "u-carol",
    status: "pendente",
    prazo: d(-2),
    prioridade: "media",
  },
  {
    id: "t-03",
    titulo: "Ligar para Rafael Menezes (lead indicado)",
    responsavelId: "u-bruno",
    status: "atrasada",
    prazo: d(2),
    prioridade: "alta",
  },
  {
    id: "t-04",
    titulo: "Onboarding do contrato Martins Imóveis",
    responsavelId: "u-bruno",
    status: "em-andamento",
    prazo: d(-3),
    prioridade: "urgente",
    clienteId: "c-01",
  },
  {
    id: "t-05",
    titulo: "Fechar escopo da 2ª fase — Andrade Engenharia",
    responsavelId: "u-bruno",
    status: "pendente",
    prazo: d(-6),
    prioridade: "media",
  },
  {
    id: "t-06",
    titulo: "Preparar apresentação para reunião Ferreira Odontologia",
    responsavelId: "u-carol",
    status: "pendente",
    prazo: d(-1),
    prioridade: "alta",
  },
  {
    id: "t-07",
    titulo: "Revisar cobrança Asaas do mês",
    responsavelId: "u-ana",
    status: "concluida",
    prazo: d(3),
    prioridade: "media",
  },
  {
    id: "t-08",
    titulo: "Atualizar catálogo de serviços no site",
    responsavelId: "u-diego",
    status: "pendente",
    prazo: d(-10),
    prioridade: "baixa",
  },
  {
    id: "t-09",
    titulo: "Renovação de contrato — Dantas Turismo (pausado)",
    responsavelId: "u-ana",
    status: "atrasada",
    prazo: d(4),
    prioridade: "alta",
    clienteId: "c-05",
  },
  {
    id: "t-10",
    titulo: "Compilar métricas de prospecção da semana",
    responsavelId: "u-carol",
    status: "concluida",
    prazo: d(1),
    prioridade: "baixa",
  },
  {
    id: "t-11",
    titulo: "Enviar contrato para assinatura — Moura Logística",
    responsavelId: "u-bruno",
    status: "concluida",
    prazo: d(9),
    prioridade: "media",
    clienteId: "c-06",
  },
  {
    id: "t-12",
    titulo: "Agendar call de kickoff com Alves & Filhos",
    responsavelId: "u-ana",
    status: "em-andamento",
    prazo: d(-2),
    prioridade: "media",
    clienteId: "c-03",
  },
];

/* ==========================================================================
 * FINANCEIRO — resumo + transacoes recentes (numeros mockados plausiveis).
 * ======================================================================== */

export const FINANCE_SUMMARY: FinanceSummary = {
  caixaAtual: 184300,
  aReceber: 96700,
  receitaMes: 71250,
  taxaInadimplencia: 0.086,
};

export const TRANSACTIONS: Transaction[] = [
  {
    id: "tx-01",
    descricao: "Mensalidade — contrato Martins Imóveis",
    parte: "Martins Imóveis",
    valor: 27500,
    tipo: "entrada",
    data: d(1),
    status: "pago",
  },
  {
    id: "tx-02",
    descricao: "Entrada — proposta fechada Carvalho Marmoraria",
    parte: "Carvalho Marmoraria",
    valor: 13400,
    tipo: "entrada",
    data: d(3),
    status: "pago",
  },
  {
    id: "tx-03",
    descricao: "Assinatura de ferramentas (Google Workspace)",
    parte: "Google",
    valor: 890,
    tipo: "saida",
    data: d(4),
    status: "pago",
  },
  {
    id: "tx-04",
    descricao: "Mensalidade — Alves & Filhos Distribuidora",
    parte: "Alves & Filhos Distribuidora",
    valor: 42000,
    tipo: "entrada",
    data: d(6),
    status: "pendente",
  },
  {
    id: "tx-05",
    descricao: "Anúncios — captação de leads (Meta Ads)",
    parte: "Meta",
    valor: 3200,
    tipo: "saida",
    data: d(7),
    status: "pago",
  },
  {
    id: "tx-06",
    descricao: "Mensalidade — Siqueira Clínica Odontológica",
    parte: "Siqueira Clínica Odontológica",
    valor: 9800,
    tipo: "entrada",
    data: d(9),
    status: "pago",
  },
  {
    id: "tx-07",
    descricao: "Mensalidade — Moura Logística",
    parte: "Moura Logística",
    valor: 33500,
    tipo: "entrada",
    data: d(11),
    status: "pendente",
  },
  {
    id: "tx-08",
    descricao: "Hospedagem e domínio (Vercel + registro)",
    parte: "Vercel",
    valor: 640,
    tipo: "saida",
    data: d(12),
    status: "pago",
  },
  {
    id: "tx-09",
    descricao: "Mensalidade — Dantas Turismo",
    parte: "Dantas Turismo",
    valor: 15600,
    tipo: "entrada",
    data: d(14),
    status: "pendente",
  },
  {
    id: "tx-10",
    descricao: "Pró-labore e salários",
    parte: "Equipe Emerge",
    valor: 38000,
    tipo: "saida",
    data: d(15),
    status: "pago",
  },
];
